[workspace]
name = "AiAssistance_agents"
version = "0.1.0"
description = "Agents for local AI Assistance (kbn)"
authors = ["DeadlySquad13 <46250621+DeadlySquad13@users.noreply.github.com>"]
channels = ["pytorch", "nvidia", "conda-forge"]
platforms = ["linux-64"]

[tasks]
#   `break-system-packages` option is set to mute ArchLinux notifications that we
# are installing package globally (in reality we aren't, it's just pixi venvs
# are recognized as global).
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check --break-system-packages -e ."
build = "echo test"
kbn = "python src/kbn/main.py"

[dependencies]
python = ">=3.14"
pandas = "*"
langchain = "*"
langchain-ollama = "*"
# numpy = "==1.26.4"

[pypi-dependencies]
# Currently this version (that is compatible with Python 3.14) is only
# available at Pypi.
langchain-chroma = "==1.1.0"
tqdm = "*"

[feature.test]
tasks = { test = "pytest" }
pypi-dependencies = { AiAssistance_agents = { path = "./", editable = true }, pytest = "==6.2.5", pytest-cov = "==2.12.1" }

[feature.lint.tasks]
lint-check = "flake8 src"

format = "black src"
format-check = "black --check --diff src"

types-check = "mypy src"

order-imports = "isort src"
order-imports-check = "isort --check --diff src"

[feature.lint.pypi-dependencies]
flake8 = "==7.0.0"
tox = "==3.24.3"
mypy = "==1.9.0"
black = "==24.3.0"
isort = "==5.13.2"

[feature.pre-commit]
tasks = { pre-commit-check = "pre-commit run --all-files" }
pypi-dependencies = { AiAssistance_agents = { path = "./", editable = true }, pre-commit = "==3.7.0" }

# [feature.quarto.tasks]
# preview-docs = "quarto preview docs"
# build-docs = "quarto render docs"

# preview-reports = "quarto preview reports"
# build-reports = "quarto render reports"
# build-reports-html = "quarto render reports --to html"
# build-reports-pdf = "quarto render reports --to pdf"

# [feature.quarto.dependencies]
# quarto = "1.4.550"

# [feature.jupyter.pypi-dependencies]
# notebook = "*"
# nbclassic = "*"
# jupyter-console = "*"

# [feature.jupyter-neovim.pypi-dependencies]
# jupynium = "*"

[environments]
default = []
dev = ["test", "lint", "pre-commit"]
# dev-ju = ["test", "lint", "jupyter", "pre-commit"]
# dev-ju-nvim = ["test", "lint", "jupyter", "jupyter-neovim", "pre-commit"]
# quarto = ["quarto", "jupyter"]
# dev-quarto = ["test", "lint", "quarto", "jupyter", "pre-commit"]
